### PR TITLE
feat(core): specify default Cache-Control for responses when not set …

### PR DESCRIPTION
**Pull request by darkweak**
…by upstream (#177)

* Add default_cache_control for core and traefik

* Move adding default Cache-Control header to bridge.go

* Add to core docs

* Add to traefik plugin docs

* Add for Caddy plugin

* Add to Caddy plugin docs

* Add code and docs for Tyk plugin

* Add Caddy plugin docs to top-level README

### CODE REVIEW

**Comment by darkweak** [comment]
@Menci Can you push on this branch instead of your fork please because it will trigger automatically the tests workflow.

**Comment by Menci** [comment]
You can add `on.pull_request` to your GitHub Actions workflow files to make every PR's commit tested in CI.

**Comment by Menci** [comment]
image

Sadly I have no permission ...

**Comment by Menci** [comment]
Let's close it and continue in #183.

**Pull request closed without merging**
