### PR TITLE
feat(chore): cache_keys regexp ordered

### LINKED ISSUE #329: cache_keys + default hide
Cache key is empty in `Cache-Status` when using the `cache_keys` directive this way:

```
cache_keys {
	".*" {
		disable_query true
	}
	".*\?something=1$" {
		disable_query false
	}
}
```

Output:
`cache-status: Souin; fwd=uri-miss; stored; key=`
or
`cache-status: Souin; hit; ttl=86361; key=`

By setting `hide false` specifically, the key is shown.

### PR DESCRIPTION
**Pull request by darkweak**
Closes #329

### CODE REVIEW

**Comment by darkweak** [comment]
@frederichoule this PR will fix the unordered cache_keys.

**Comment by frederichoule** [comment]
Great, I'll try it. Since it didn't work I'm now using `matchers` on Caddy directly to match different query string to different caching parameters, but I'll give it a try as soon as it's released.

**Comment by frederichoule** [comment]
Are you also taking care of https://github.com/darkweak/souin/issues/329 ?

**Comment by darkweak** [comment]
@frederichoule indeed! 😉

**Comment by frederichoule** [comment]
Good job @darkweak ! Can you bump up version in https://github.com/caddyserver/cache-handler also? Thanks!

**Pull request merged**
