### PR TITLE
Fix missing key configuration for traefik plugin

### PR DESCRIPTION
**Pull request by yongzhang**
Fixes https://github.com/darkweak/souin/issues/352.

Tests:

```
curl -vvv -H "Host: whoami.example.com" http://localhost:8080/cache?a=b
```

With all true:
```
          default_cache:
            key:
              disable_body: true
              disable_host: true
              disable_method: true
              disable_query: true
              hide: false
```
```
< Cache-Status: Souin; fwd=uri-miss; stored; key=http-/cache
```

With all false:
```
          default_cache:
            key:
              disable_body: false
              disable_host: false
              disable_method: false
              disable_query: false
              hide: false
```
```
< Cache-Status: Souin; fwd=uri-miss; stored; key=GET-http-whoami.example.com-/cache?a=b
```

Hide key:
```
            key:
              disable_body: false
              disable_host: false
              disable_method: false
              disable_query: false
              hide: true
```
```
< Cache-Status: Souin; fwd=uri-miss; stored; key=
```

### CODE REVIEW

**Comment by yongzhang** [comment]
@darkweak Please review, thanks.

**Comment by darkweak** [comment]
Thank you for this contribution I'll have some free time to review that today!

**Review by darkweak — APPROVED** [review]
LGTM if the pipeline is good it can be merged.

**Comment by yongzhang** [comment]
Added a tiny update to fix that weird coding.

**Comment by darkweak** [comment]
does the parseBool function needed? It's an interface so I guess we could just cast it as boolean right?

**Comment by yongzhang** [comment]
> does the parseBool function needed? It's an interface so I guess we could just cast it as boolean right?

good idea, updated, but a lot of vendor updates from `darkweak` pkg, not sure if they're expected, please have a look that.

**Comment by yongzhang** [comment]
> > does the parseBool function needed? It's an interface so I guess we could just cast it as boolean right?
> 
> good idea, updated, but a lot of vendor updates from `darkweak` pkg, not sure if they're expected, please have a look that.

If I tidy go mod and update vendor, it will have import errors in traefik, how did you finish this part before?

**Comment by darkweak** [comment]
You have to go to the Traefik directory and there is a Makefile in it (inside each plugins) and run `make vendor`, it should do the trick.

**Comment by darkweak** [comment]
You can cast an interface to an implementation using `variable.(your_type_cast)` in go (e.g. `keyV.bool`)

**Comment by yongzhang** [comment]
> You can cast an interface to an implementation using `variable.(your_type_cast)` in go (e.g. `keyV.bool`)

We can't, because in this case, the interface will be recogized as string so can't convert it to bool.

**Comment by darkweak** [comment]
You're right, I didn't try the cdn group and there is `cdn.Dynamic = cdnV.(bool)` that is failing. Keep the `parseBool` function then and can you update the `cdn.Dynamic = cdnV.(bool)` to use your method?

**Review by darkweak — APPROVED** [review]
LGTM! ✅

**Comment by darkweak** [comment]
Thank you so much @yongzhang for your contribution! 🚀

**Pull request merged**
