### PR TITLE
fix(core): Stabilization v1.6.x

### LINKED ISSUE #246: Random panic with caddy plugin
I see the following panic randomly on my raspberry pi. I don't see a pattern yet. Any ideas?

```
panic: Header called after Handler finished
goroutine 79751 [running]:
net/http.(*http2responseWriter).Header(0xbaa2070)
        net/http/h2_bundle.go:6359 +0x80
github.com/darkweak/souin/plugins.(*CustomWriter).Header(...)
        github.com/darkweak/souin@v1.6.18/plugins/base.go:39
github.com/darkweak/souin/plugins/caddy.(*SouinCaddyPlugin).ServeHTTP.func1({0x1d7d938, 0xc4ae130}, 0x69e1f00)
        github.com/darkweak/souin/plugins/caddy@v0.0.0-20220802191641-cb8865f626c1/httpcache.go:129 +0xec
github.com/darkweak/souin/plugins.DefaultSouinPluginCallback.func3()
        github.com/darkweak/souin@v1.6.18/plugins/base.go:187 +0xa0
created by github.com/darkweak/souin/plugins.DefaultSouinPluginCallback
        github.com/darkweak/souin@v1.6.18/plugins/base.go:183 +0x7b0
```

### LINKED ISSUE #247: Prevent authenticated users responses from being cached
Actually, Souin doesn't follow the spec about the authenticated users. It caches responses that it shouldn't!

Implement in the `UpdateCacheEventually` method https://github.com/darkweak/souin/blob/master/rfc/bridge.go#L107

Fixes https://github.com/caddyserver/cache-handler/issues/34

### LINKED ISSUE #248: Surrogate key flush bug - round 2 - v1.6.18
This seems to have been broken in the latest release. Works fine in v1.6.17

```
2022/09/10 12:33:21 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/darkweak/souin/plugins/caddy@cb8865f626c13f68d1596f1df2026d5c7239edbf github.com/caddyserver/caddy/v2@v2.5.2 
go: downloading github.com/darkweak/souin/plugins/caddy v0.0.0-20220802191641-cb8865f626c1
go: downloading github.com/darkweak/souin v1.6.18

```

Inital GET response headers: `/api/shop/get`

```
Access-Control-Allow-Origin: *
Cache-Status: Souin; fwd=uri-miss; stored
Content-Type: application/json
Date: Sat, 10 Sep 2022 12:28:56 GMT
Surrogate-Key: awdad-4lpusdqw.localhost, product-86dbdcb8-ee9e-4f9d-8855-22be4a5cd6a5, product-fb8742c0-c468-42a6-86eb-7ef5ffd26940, category-3aae51db-946a-4984-9e7e-d28276afa5dc
Transfer-Encoding: chunked
```

Refresh:

```
Access-Control-Allow-Origin: *
Age: 49
Cache-Status: Souin; hit; ttl=3551
Content-Type: application/json
Date: Sat, 10 Sep 2022 12:28:56 GMT
Surrogate-Key: awdad-4lpusdqw.localhost, product-86dbdcb8-ee9e-4f9d-8855-22be4a5cd6a5, product-fb8742c0-c468-42a6-86eb-7ef5ffd26940, category-3aae51db-946a-4984-9e7e-d28276afa5dc
Transfer-Encoding: chunked
```

Looks good so far. Now trigger a cache flush for `awdad-4lpusdqw.localhost`:

```
caddy_1                | {"level":"DEBUG","time":"2022-09-10T12:30:27.791Z","caller":"providers/common.go:152","message":"Purge the tag awdad-4lpusdqw.localhost"}
```

Response still cached:

```
Access-Control-Allow-Origin: *
Age: 138
Cache-Status: Souin; hit; ttl=3462
Content-Type: application/json
Date: Sat, 10 Sep 2022 12:28:56 GMT
Surrogate-Key: awdad-4lpusdqw.localhost, product-86dbdcb8-ee9e-4f9d-8855-22be4a5cd6a5, product-fb8742c0-c468-42a6-86eb-7ef5ffd26940, category-3aae51db-946a-4984-9e7e-d28276afa5dc
Transfer-Encoding: chunked
```

### PR DESCRIPTION
**Pull request by darkweak**
This PR will handle the necessary fixes to the v1.6.x stab.
- [x] Move the `Send` method to the `plugins` package.
- [x] Fix ugly custom writers in some plugins.
- [ ] Stream the response (delayed to the future).
- [x] Handle the `ESI` tags properly. (probably in another PR)

Closes #246 
Closes #247 
Closes #248

### CODE REVIEW

**Comment by mattvb91** [comment]
Just fyi ive just given this a test run on the latest commit [306479a](https://github.com/darkweak/souin/pull/245/commits/306479a3e61253971113e2788c93df51cd6f2e69) and I get the following:

```
caddy_1                | {"level":"debug","ts":1662009096.348341,"logger":"http.handlers.cache","msg":"Incoming request: &{Method:GET URL:/sw.js Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en,de;q=0.9,en-IE;q=0.8,en-US;q=0.7] Cache-Control:[max-age=0] Connection:[keep-alive] Cookie:[] Date:[Thu, 01 Sep 2022 05:11:36 UTC] Sec-Ch-Ua:[\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:[\"Linux\"] Sec-Fetch-Dest:[document] Sec-Fetch-Mode:[navigate] Sec-Fetch-Site:[none] Sec-Fetch-User:[?1] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:localhost Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:172.18.0.1:47430 RequestURI:/sw.js TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc0001f67b0}"}
caddy_1                | panic: runtime error: invalid memory address or nil pointer dereference
caddy_1                | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b0efb8]
caddy_1                | 
caddy_1                | goroutine 56 [running]:
caddy_1                | github.com/xujiajun/nutsdb.(*Tx).getTxID(0xc0005bc540?)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/tx.go:123 +0x18
caddy_1                | github.com/xujiajun/nutsdb.newTx(0x0, 0x0)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/tx.go:111 +0x9f
caddy_1                | github.com/xujiajun/nutsdb.(*DB).Begin(0x0, 0x4?)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/tx.go:85 +0x25
caddy_1                | github.com/xujiajun/nutsdb.(*DB).managed(0x150?, 0xa0?, 0xc000374c08)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/db.go:958 +0x39
caddy_1                | github.com/xujiajun/nutsdb.(*DB).View(...)
caddy_1                |        github.com/xujiajun/nutsdb@v0.9.0/db.go:295
caddy_1                | github.com/darkweak/souin/cache/providers.(*Nuts).Prefix(0xc000374d98?, {0xc00032f098?, 0x1fc5afe?}, 0x6?)
caddy_1                |        github.com/darkweak/souin@v1.6.19-0.20220901043136-306479a3e612/cache/providers/nutsProvider.go:137 +0x72
caddy_1                | github.com/darkweak/souin/rfc.CachedResponse({0x23ee910, 0xc0003f4ac0}, 0xc0002e6b00, {0xc00032f098, 0x14}, {0x0?, 0x0?})
caddy_1                |        github.com/darkweak/souin@v1.6.19-0.20220901043136-306479a3e612/rfc/bridge.go:23 +0x1fb
caddy_1                | github.com/darkweak/souin/plugins.DefaultSouinPluginCallback.func1(0xe0?, {0x23f1c20, 0xc00067b9e0}, {0xc00032f098, 0x14})
caddy_1                |        github.com/darkweak/souin@v1.6.19-0.20220901043136-306479a3e612/plugins/base.go:137 +0xf8
caddy_1                | created by github.com/darkweak/souin/plugins.DefaultSouinPluginCallback
caddy_1                |        github.com/darkweak/souin@v1.6.19-0.20220901043136-306479a3e612/plugins/base.go:135 +0x4e5

```

Interestingly enough the `/sw.js` that triggers the error should actually result in a 404 because that file doesnt exist maybe that can help you trace it?

**Comment by darkweak** [comment]
I think that's an issue with your nuts db.
The patch for that could be to silently handle the panic with the recover, just log the panic error and return an empty response if it panics. WDYT?

**Comment by mattvb91** [comment]
hmm not sure what you mean im just using the default souin nutsdb that ships with the plugin I havent made any custom changes?

**Comment by darkweak** [comment]
I mean, it's probably a nutsdb issue because it panics in the nuts codebase. And I downgrade from `v0.10.0` to `v0.9.0` and maybe that they're not compatible.

**Comment by mattvb91** [comment]
Im not familiar enough with GO to be of help tbh but surely there must be a way to `try { } catch` wherever souin interacts with nutsdb or other libs and just log the error that the underlying lib threw? (Maybe thats what you suggested above)

Definitely feels weird that nutsdb is as flakey as it is

**Comment by darkweak** [comment]
Yes that's what I said, it's a kind of try catch.

We don't have that issue with others providers. As I said, I have downgrade the nutsdb version so maybe your db is considered as corrupted because of this downgrade.

**Comment by mattvb91** [comment]
Pretty sure we switched to nutsdb due to badger also being broken?

**Comment by darkweak** [comment]
No we switched from badger because it had some database corruptions 😄

**Comment by mattvb91** [comment]
@darkweak I've just ran the latest commit a83401d and plugged dragonfly in with it and im back to having cache corruption:

image

I will try it with standard redis now and report back. But it does look more and more like the cache corruption issues stem from souin itself I cant imagine all of these third party libraries having the same issue its too much of a coincidence at this point.

**Comment by darkweak** [comment]
You're right @mattvb91 I think it's a Souin issue (maybe either a race condition or a bad response encoding header). Let me investigate on that.

**Pull request merged**
